SELECT 
    total_scores.SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM (
    SELECT 
        EMP_NO,
        SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) total_scores
JOIN HR_EMPLOYEES E ON total_scores.EMP_NO = E.EMP_NO
WHERE total_scores.SCORE = (
    SELECT SUM(SCORE)
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
);