SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '김치', '국', '식용유')
  AND PRICE = (
      SELECT MAX(PRICE)
      FROM FOOD_PRODUCT F2
      WHERE F2.CATEGORY = FOOD_PRODUCT.CATEGORY
  )
ORDER BY MAX_PRICE DESC;